core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += [
    path('api-token-auth/', views.obtain_auth_token)
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
from .api import *

app_name = 'products'
urlpatterns = [    
    
    path('<int:pk>/viewproduct', views.ViewProduct.as_view(), name='viewproduct'),
    path('<int:pk>/ownedproducts', views.OwnedProductsView.as_view(), name='ownedproducts'),    
    path('<int:pk>/createproduct', views.CreateProductView.as_view(), name='createproduct'),
    path('<int:pk>/updateproduct', views.UpdateProductView.as_view(), name='updateproduct'),
    path('<int:pk>/productstatus', views.ProductStatusView.as_view(), name='productstatus'),
    path('<int:pk>/undercategory', views.UnderCategory.as_view(), name='undercategory'),

    # AllowAny
    path('api/getproduct/', ProductViewSet.as_view({'get': 'get_product'})),
    path('api/getproducts/', ProductViewSet.as_view({'get': 'get'})),
    path('api/saleproducts/', ProductViewSet.as_view({'get': 'get_on_sale'})),
    path('api/categories/', ProductViewSet.as_view({'get': 'get_categories'})),
    path('api/undercategories/', ProductViewSet.as_view({'get': 'under_category'})),
    path('api/search/', ProductViewSet.as_view({'post': 'search'})),                 

    # ProductForAuthUser
    path('api/addproduct/', ProductForAuthUserViewSet.as_view({'post': 'post'})),
    path('api/updateproduct/', ProductForAuthUserViewSet.as_view({'post': 'put'})),
    path('api/deleteproduct/', ProductForAuthUserViewSet.as_view({'delete': 'delete'})),

    # AuthSeller
    path('api/ownedproducts/', AuthSellerViewSet.as_view({'get': 'get_owned_products'})),
    path('api/productstatus/', AuthSellerViewSet.as_view({'get': 'product_status'})),
    path('api/shipitem/', AuthSellerViewSet.as_view({'get': 'ship_item'})),
    path('api/addorder/', AuthSellerViewSet.as_view({'post': 'create_order'})),     
    path('api/addstock/', AuthSellerViewSet.as_view({'post': 'add_stock'})), 

    # AuthBuyer    
    path('api/orderedproducts/', AuthBuyerViewSet.as_view({'get': 'get_ordered_products'})),     
    path('api/orderstatus/', AuthBuyerViewSet.as_view({'get': 'order_status'})),    

    # AdminUser
    path('api/adminorderedproducts/', AdminUserViewSet.as_view({'get': 'admin_get_ordered_products'})),   
    path('api/adminownedproducts/', AdminUserViewSet.as_view({'get': 'admin_get_owned_products'})),
    path('api/userorders/', AdminUserViewSet.as_view({'get': 'admin_get_user_orders'})),

    # Cart
    path('api/countitem/', CartViewSet.as_view({'get': 'item_count'})),
    path('api/addtocart/', CartViewSet.as_view({'post': 'add_to_cart'})),
    path('api/updateitem/', CartViewSet.as_view({'post': 'update_item'})),    
    path('api/removeitem/', CartViewSet.as_view({'delete': 'remove_item'})),


    # Payment
    path('api/addpayment/', PaymentViewSet.as_view({'post': 'add_payment'})),     
]

products/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import BooleanField, CharField, SlugField
from datetime import timedelta, datetime

from django.db.models.fields.related import ForeignKey
from users.models import CustomUser


class Category(models.Model):

    name = CharField(max_length=50)
    slug = SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class SubCategory(models.Model):

    img = models.ImageField(blank=True, null=True, upload_to='category/', default='default.png')
    name = CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
        

class Product(models.Model):

    id = models.AutoField(primary_key=True, unique=True)
    product_name = models.CharField(max_length=250)
    product_image = models.ImageField(upload_to='product/', default='product/default.png')
    description = models.CharField(max_length=250)
    location = models.CharField(max_length=250, blank=True, null=True)  
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)  
    shipping_fee = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    discount = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    is_discounted = models.BooleanField(default=False)    
    quantity = models.IntegerField(default=0)
    is_available = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)    
    seller = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.product_name


class OrderItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)    
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    is_shipping = models.BooleanField(default=False)
    shipping_duration = models.DurationField(blank=True, null=True)

    def __str__(self):
        return str(self.product)


class Order(models.Model):
    
    buyer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)  
    date_ordered = models.DateTimeField(auto_now_add=True)    
    is_completed = models.BooleanField(default=False)
    order_item = models.ManyToManyField(OrderItem, related_name='order')

    def __str__(self):
        return str(self.date_ordered)


class CartItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)   
    quantity = models.IntegerField()

    def __str__(self):
        return str(self.product)


class Cart(models.Model):

    buyer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)      
    is_checkedout = models.BooleanField(default=False)
    cart_item = models.ManyToManyField(CartItem, related_name="cart")    

    def __str__(self):
        return str(self.buyer)


class OrderPayment(models.Model):

    amount = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(auto_now_add=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment_method = models.CharField(max_length=20, default="COD")
    

class CODPayment(models.Model):

    address = models.CharField(max_length=100)    
    order_payment = models.ForeignKey(OrderPayment, on_delete=models.CASCADE)

class CardPayment(models.Model):
    
    name = models.CharField(max_length=50)
    card_number = models.IntegerField()
    cvv = models.IntegerField()
    expiration = models.CharField(max_length=10)    
    order_payment = models.ForeignKey(OrderPayment, on_delete=models.CASCADE)

products/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.base import TemplateView
from .models import Category, CustomUser, Product, SubCategory


class OwnedProductsView(TemplateView):
        
    template_name = "products/owned_products.html"
    # def get(self, request, *args, **kwargs):
    #     current_user = CustomUser.objects.get(pk=kwargs.get('pk'))
    #     owned_products = Product.objects.filter(seller=request.user)
    #     return render(request, "products/owned_products.html", {'current_user': current_user, 'owned_products': owned_products})


class ShowCategoryView(TemplateView):
    
    def get(self, request):
        categories = Category.objects.all()
        sub_categories = SubCategory.objects.all()

        context = {
            'categories': categories,
            'sub_categories': sub_categories,
        }
        return render(request, 'dashboard.html', context)

class CreateProductView(TemplateView):    
    
    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        sub_categories = SubCategory.objects.all()

        context = {
            'categories': categories,
            'sub_categories': sub_categories,
        }
        return render(request, 'products/create_product.html', context)


class UpdateProductView(TemplateView):    
    
    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        sub_categories = SubCategory.objects.all()
        instance = Product.objects.get(pk=kwargs.get('pk'))
        
        context = {
            'categories': categories,
            'sub_categories': sub_categories,
            'instance': instance,
        }
        return render(request, 'products/update_product.html', context)

class ViewProduct(TemplateView):
    template_name = 'products/product_page.html'   


class ProductStatusView(TemplateView):
    template_name = "products/product_status.html"


class UnderCategory(TemplateView):
    template_name = "products/under_category.html"

templates/products/create_product.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/create.css' %}">
{% endblock %}

{% block content %}

    <div class="container" id="create">
        <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
        <form id="addproduct" class="needs-validation" enctype="multipart/form-data" novalidate>          
            {% csrf_token %}  
            <div class="leftside">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="product_name">Product Name</label>
                        <input type="text" class="form-control" id="product_name" placeholder="Product" required>
                        <div class="invalid-feedback">Please enter product name.</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="product_image">Product Image</label>
                        <input type="file" class="form-control-file" id="product_image">                        
                    </div>
                </div>
                <div class="form-group">
                    <label for="description">Product Description</label>
                    <input type="text" class="form-control" id="description" required>
                    <div class="invalid-feedback">Please enter product description.</div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="location">Product Location</label>
                        <input type="text" class="form-control" id="location" placeholder="ex: Manila" required>
                        <div class="invalid-feedback">Please enter product location.</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="quantity">Quantity</label>
                        <input type="text" class="form-control" id="quantity" required>
                        <div class="invalid-feedback">Please enter product quantity.</div>
                    </div>
                </div>      
                <div class="form-row">
                    <div class="form-group col-md-4 ml-4">
                        <input class="form-check-input" type="checkbox" value="" id="is_avalable" checked>
                        <label class="form-check-label" for="is_avalable">Available</label>
                    </div>  
                    <div class="form-group col-md-4">
                        <input class="form-check-input" type="checkbox" value="" id="is_discounted" onclick="enable_discount()">
                        <label class="form-check-label" for="is_discounted">Discounted</label>
                    </div>                      
                </div>                 
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="price">Price</label>
                        <input type="text" class="form-control" id="price" min="0" max="10" step="0.25" value="0.00" required>
                        <div class="invalid-feedback">Please enter product price.</div>
                    </div>                    
                    <div class="form-group col-md-4">
                        <label for="shipping_fee">Shipping Fee</label>
                        <input type="text" class="form-control" id="shipping_fee"  min="0" max="10" step="0.25" value="0.00">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="discount">Discount</label>
                        <input type="text" class="form-control" id="discount"  min="0" max="10" step="0.25" value="0.00">
                    </div>
                </div>               
                <button type="submit" class="btn btn-primary">Add Product</button>
            </div>
            
            <label class="ml-2" for="categories">
                Categories
            </label>
            <div class="scrollable">                 
                {% for category in categories %}               
                    <div class="form-check" id="category">
                        <input class="form-check-input categorycb" type="checkbox" value="{{ category.id }}" onclick="set_category_id('{{ category.id }}')" id="product_category" >
                        <label class="form-check-label" for="product_category">
                            {{ category.name }}
                        </label>
                        {% for sub_category in sub_categories %}
                            {% if sub_category.category == category %}
                                <div class="form-check" id="sub_category">
                                    <input class="form-check-input" type="checkbox" value="{{ sub_category.id }}" onclick="set_subcategory_id('{{ sub_category.id }}')" id="product_subcategory">
                                    <label class="form-check-label" for="product_subcategory">
                                        {{ sub_category.name }}
                                    </label>                                    
                                </div>
                            {% endif %}
                        {% endfor %}             
                    </div>             
                {% endfor %}
            </div>            
        </form>                      
    </div>
    
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'products/js/create.js' %}"></script>
{% endblock %}

templates/products/owned_products.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock %}
{% block content %}
  
  <div class="container" id="check_owned">    
    <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
    <a href="{% url 'products:createproduct' user.id %}" class="btn btn-dark">
      Add Product
    </a>
    <h3 class="mt-4">Products</h3>
    <hr>
    <div class="row" id="owned">          
    </div>
    <form>
      {% csrf_token %}
    </form>  
    <br>    
  </div>
  
{% endblock %}

{% block extra_js %}
  <script type="text/javascript" src="{% static 'products/js/owned.js' %}"></script>
{% endblock %}

templates/products/product_page.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/view.css' %}"> 
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>      
{% endblock %}


{% block content %}
<div class="product" id="productpage">
    <input  type="hidden" value="{{ request.user.is_authenticated}}" id="auth">
    <input type="hidden" id="product_id" value="{{ view.kwargs.pk }}">
    <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
    <p>{{ view.kwargs.seller }}</p>    
</div>
{% csrf_token %}
{% endblock %}


{% block extra_js %}
    <script type="text/javascript" src="{% static 'products/js/view.js' %}"></script>
    <script type="text/javascript" src="{% static 'products/js/item_count.js' %}"></script>
{% endblock %}

templates/products/product_status.html
{% extends 'base.html' %}
{% load static %}

{% block head%}
  <link rel="stylesheet" type="text/css" href="{% static 'products/css/status.css' %}">
{% endblock %}

{% block content %}
<div class="container" id="status">
  <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
  <div class="row">    
    <div class="col-md-5">
      <h4>Stock</h4>
      <table class="table table-hover text-center">
        <thead>
          <tr>            
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>            
            <th scope="col">Stockin Value</th>
            <th scope="col"></th> 
  
          </tr>
        </thead>
        <tbody id="product-stock">
          
        </tbody>
      </table>
    </div>
    <div class="col-md-7">
      <h4>Orders</h4>
      <table class="table table-hover text-center">
        <thead>
          <tr>            
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>            
            <th scope="col">Date Ordered</th> 
            <th scope="col">Status</th>
            <th scope="col">Ship Duration</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody id="product-status">
          
        </tbody>
      </table>
    </div>
  </div>      
</div>
{% endblock %}

{% block extra_js %}
  <script type="text/javascript" src="{% static 'products/js/status.js' %}"></script>
{% endblock %}

templates/products/under_category.html
{% extends 'base.html' %}
{% load static %}

{% block head%}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
    <br>
    <h3>Items </h3>
    <hr>
    <div class="row layout-margin-8 mt-4">  
        <div class="card-deck" id="products">

        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'products/js/under_category.js' %}"></script>
{% endblock %}

    

templates/products/update_product.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/create.css' %}">
{% endblock %}

{% block content %}

    <div class="container" id="update">        
        <input  type="hidden" value="{{ instance.seller.id }}" id="seller">
        <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
        <form id="updateProduct" method="POST" enctype="multipart/form-data">          
            {% csrf_token %}  
            <div class="leftside">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="product_name">Product Name</label>
                        <input type="text" class="form-control" id="product_name" placeholder="Product" value="{{ instance.product_name }}">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="product_image">Product Image</label>
                        <input type="file" class="form-control-file" id="product_image" value="{{ instance.product_image }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="description">Product Description</label>
                    <input type="text" class="form-control" id="description" value="{{ instance.description }}">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="location">Product Location</label>
                        <input type="text" class="form-control" id="location" placeholder="ex: Manila" value="{{ instance.location }}">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="quantity">Quantity</label>
                        <input type="text" class="form-control" id="quantity" value="{{ instance.quantity }}">
                    </div>
                </div>      
                <div class="form-row">
                    <div class="form-group col-md-4 ml-4">
                        {% if instance.is_avalable == 'True' %}
                            <input class="form-check-input" type="checkbox" value="" id="is_avalable" checked>
                        {% else %}
                            <input class="form-check-input" type="checkbox" value="" id="is_avalable">
                        {% endif %}
                        <label class="form-check-label" for="is_avalable">Available</label>
                    </div>  
                    <div class="form-group col-md-4">
                        <input class="form-check-input" type="checkbox" value="" id="is_discounted" onclick="enable_discount()" value="{{ instance.is_discounted }}">
                        <label class="form-check-label" for="is_discounted">Discounted</label>
                    </div>                      
                </div>                 
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="price">Price </label>
                        <input type="text" class="form-control" id="price" value="{{ instance.price }}" onchange="setTwoNumberDecimal()" min="0" max="10" step="0.25" value="0.00">
                    </div>                    
                    <div class="form-group col-md-4">
                        <label for="shipping_fee">Shipping Fee</label>
                        <input type="text" class="form-control" id="shipping_fee" value="{{ instance.shipping_fee }}" onchange="setTwoNumberDecimal()" min="0" max="10" step="0.25" value="0.00">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="discount">Discount</label>
                        <input type="text" class="form-control" id="discount" value="{{ instance.discount }}" onchange="setTwoNumberDecimal()" min="0" max="10" step="0.25" value="0.00">
                    </div>
                </div>               
                <button type="submit" class="btn btn-warning">Update Product</button>
            </div>
            
            <label class="ml-2" for="categories">
                Categories
            </label>
            <div class="scrollable">                 
                {% for category in categories %}               
                    <div class="form-check" id="categories">
                        {% if category == instance.product_category %}                        
                            <input class="form-check-input" type="checkbox" value="{{ category.id }}" onclick="set_category_id('{{ category.id }}')" id="product_category" checked>
                        {% else %}
                            <input class="form-check-input" type="checkbox" value="{{ category.id }}" onclick="set_category_id('{{ category.id }}')" id="product_category">
                        {% endif %}
                        <label class="form-check-label" for="product_category">
                            {{ category.name }}
                        </label>
                        {% for sub_category in sub_categories %}
                            {% if sub_category.category == category %}
                                <div class="form-check" id="sub_category">
                                    {% if sub_category == instance.product_subcategory %}  
                                        <input class="form-check-input" type="checkbox" value="{{ sub_category.id }}" onclick="set_subcategory_id('{{ sub_category.id }}')" id="product_subcategory" checked>
                                    {% else %}
                                        <input class="form-check-input" type="checkbox" value="{{ sub_category.id }}" onclick="set_subcategory_id('{{ sub_category.id }}')" id="product_subcategory">
                                    {% endif %}
                                    <label class="form-check-label" for="product_subcategory">
                                        {{ sub_category.name }}
                                    </label>
                                </div>
                            {% endif %}
                        {% endfor %}              
                    </div>             
                {% endfor %}
            </div>            
        </form>                        
    </div>
    
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'products/js/update.js' %}"></script>
{% endblock %}