core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += [
    path('api-token-auth/', views.obtain_auth_token)
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
from .api import *

app_name = 'products'
urlpatterns = [    
    
    path('<int:pk>/viewproduct', views.ViewProduct.as_view(), name='viewproduct'),
    path('<int:pk>/ownedproducts', views.OwnedProductsView.as_view(), name='ownedproducts'),    
    path('<int:pk>/createproduct', views.CreateProductView.as_view(), name='createproduct'),
    path('<int:pk>/updateproduct', views.UpdateProductView.as_view(), name='updateproduct'),
    path('<int:pk>/productstatus', views.ProductStatusView.as_view(), name='productstatus'),
    path('<int:pk>/undercategory', views.UnderCategory.as_view(), name='undercategory'),

    # AllowAny
    path('api/getproduct/', ProductViewSet.as_view({'get': 'get_product'})),
    path('api/getproducts/', ProductViewSet.as_view({'get': 'get'})),
    path('api/saleproducts/', ProductViewSet.as_view({'get': 'get_on_sale'})),
    path('api/categories/', ProductViewSet.as_view({'get': 'get_categories'})),
    path('api/undercategories/', ProductViewSet.as_view({'get': 'under_category'})),
    path('api/search/', ProductViewSet.as_view({'post': 'search'})),                 

    # ProductForAuthUser
    path('api/addproduct/', ProductForAuthUserViewSet.as_view({'post': 'post'})),
    path('api/updateproduct/', ProductForAuthUserViewSet.as_view({'post': 'put'})),
    path('api/deleteproduct/', ProductForAuthUserViewSet.as_view({'delete': 'delete'})),

    # AuthSeller
    path('api/ownedproducts/', AuthSellerViewSet.as_view({'get': 'get_owned_products'})),
    path('api/productstatus/', AuthSellerViewSet.as_view({'get': 'product_status'})),
    path('api/shipitem/', AuthSellerViewSet.as_view({'get': 'ship_item'})),
    path('api/addorder/', AuthSellerViewSet.as_view({'post': 'create_order'})),     
    path('api/addstock/', AuthSellerViewSet.as_view({'post': 'add_stock'})), 

    # AuthBuyer    
    path('api/orderedproducts/', AuthBuyerViewSet.as_view({'get': 'get_ordered_products'})),     
    path('api/orderstatus/', AuthBuyerViewSet.as_view({'get': 'order_status'})),    

    # AdminUser
    path('api/adminorderedproducts/', AdminUserViewSet.as_view({'get': 'admin_get_ordered_products'})),   
    path('api/adminownedproducts/', AdminUserViewSet.as_view({'get': 'admin_get_owned_products'})),
    path('api/userorders/', AdminUserViewSet.as_view({'get': 'admin_get_user_orders'})),

    # Cart
    path('api/countitem/', CartViewSet.as_view({'get': 'item_count'})),
    path('api/addtocart/', CartViewSet.as_view({'post': 'add_to_cart'})),
    path('api/updateitem/', CartViewSet.as_view({'post': 'update_item'})),    
    path('api/removeitem/', CartViewSet.as_view({'delete': 'remove_item'})),


    # Payment
    path('api/addpayment/', PaymentViewSet.as_view({'post': 'add_payment'})),     
]

users/urls.py
from django.urls import path
from . import views
from users.api import UserViewSet

app_name = 'users'
urlpatterns = [    
    
    path('login/', views.LoginView.as_view(), name="userlogin"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('<int:pk>/updateuser/', views.UpdateUserView.as_view(), name="updateuser"),
    path('userlist/', views.UserListView.as_view(), name="userlist"),
    path('<int:pk>/userpage/', views.UserPageView.as_view(), name="userpage"),
    path('<int:pk>/usercart/', views.UserCartView.as_view(), name="usercart"),
    path('<int:pk>/payment/', views.UserPayment.as_view(), name="payment"),
    path('<int:pk>/orderstatus/', views.OrderStatus.as_view(), name="orderstatus"),

    path('api/getuser/', UserViewSet.as_view({'get': 'get'})),
    path('api/getusers/', UserViewSet.as_view({'get': 'userlist'})),    
    path('api/updateuser/', UserViewSet.as_view({'post': 'update_user'})),
    path('api/users/register/', UserViewSet.as_view({'post': 'post'})),
    path('api/login/', UserViewSet.as_view({'post': 'userlogin'})),
    path('api/logout/', UserViewSet.as_view({'get': 'userlogout'})),

    
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>    
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'users/css/app.css' %}">       -->
                    
        {% block head %}
        {% endblock %}
    </head>

<body>    
    {% include 'nav.html' %}
    <br>

    {% block home %}               
    {% endblock %}    
    
    {% block content %}        
    {% endblock %}    
    
    {% block extra_js %}
    {% endblock %}      
</body>
<!-- <footer class="page-footer font-small blue pt-4" style="background-color: rgba(0, 0, 0, 0.05);">
    <div class="footer-copyright text-center py-3">© 2021 Copyright:
        <a>ASTA Softwares</a>
    </div>
</footer> -->
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}
<div class=container>        
    <input  type="hidden" value="{{ request.user.is_authenticated}}" id="auth">
    <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
    <nav class="navbar navbar-light justify-content-center mt-4">
        <div class="form-inline">            
            <label for="category">Category &nbsp;</label>
            <select class="form-control text-center" id="category">
                <option value="">All</option>                
                {% for category in categories %}
                    <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}
            </select>  
            <label for="subcategory">&nbsp; Subcategory &nbsp;</label>
            <select class="form-control text-center" id="subcategory">
                <option value="">All</option>
                {% for subcategory in sub_categories %}
                    <option value="{{ subcategory.name }}">{{ subcategory.name }}</option>
                {% endfor %}
            </select>  
            &nbsp;          
            <!-- <button type="button" class="btn btn-primary btn-lg mr-3" id="btnSort">Sort</button> -->
            
            <input class="form-control mr-sm-2" type="search" placeholder="Search Product" aria-label="Search" id="search" onchange="search()">            
        </div>
    </nav>
    <br>
    <h3>Featured Items </h3>
    <hr>
    <div class="row layout-margin-8 mt-4">  
        <div class="card-deck" id="featured">

        </div>
    </div>          
    <br>    
    <h3>Most Popular</h3>
    <hr>
    <div class="row layout-margin-8 mt-4">  
        <div class="card-deck" id="popular">

        </div>
    </div>          
    <br>   
    <h3>Sale Items</h3>
    <hr>
    <div class="row layout-margin-8 mt-4">  
        <div class="card-deck" id="sale">

        </div>
    </div>          
    <br>   
    <h3>Category</h3>    
    <hr>
    <div class="row layout-margin-8 mt-4">  
        <div class="card-deck" id="categories">

        </div>
    </div>  
</div>


{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'main.js' %}"></script>
{% endblock %}  

templates/nav.html
{% load static %}

<html>
<body>
    <head>
        <script type="text/javascript" src="{% static 'users/js/logout.js' %}"></script>
        <script type="text/javascript" src="{% static 'products/js/item_count.js' %}"></script>
    </head>

    <nav class="navbar navbar-expand-md" style="border-bottom: 3px solid rgb(42, 133, 139);">
        <div class="container-fluid" >
            <div class="navbar-collapse collapse w-100 ">
                <a href="{% url 'users:dashboard' %}" class="btn btn-outline-dark">Home Page</a>
            </div>
            <h1 class="navbar-brand"> Ecomm </h1>
            <div class="container">
                <div class="navbar-collapse collapse w-100 ">
                    <div class="navbar-nav ml-auto"> 
                        {% if user.is_authenticated %} 
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>                        
                            <div class="collapse navbar-collapse" id="navbarNavDropdown">                              
                                <ul class="navbar-nav">        
                                    <li class="nav-item">
                                        <a href="{% url 'users:usercart' user.id %}" class="nav-link navbar-link-2 waves-effect text-black">
                                        <span class="badge badge-pill badge-danger" id="count"></span>
                                        <i class="bi bi-cart"></i></i>
                                        </a>
                                    </li>    
                                </ul>
                                <ul class="navbar-nav">                                                                
                                    <li class="nav-item dropdown .dropdown-menu-right">                                       
                                        <a class="nav-link dropdown-toggle btn btn-outline-dark offset-md-0 w-100"  id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ user.get_full_name }}
                                        </a>                                         
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                            {% if user.is_seller %}
                                                <a class="dropdown-item" href="{% url 'products:ownedproducts' user.pk %}">Products</a>      
                                            {% endif %}
                                            {% if user.is_superuser %}
                                                <a class="dropdown-item" href="{% url 'users:userlist' %}">Users</a>      
                                            {% endif %}
                                            <a class="dropdown-item" href="{% url 'users:orderstatus' user.id %}">Order Status</a>
                                            <!-- <a class="dropdown-item" href="{% url 'users:usercart' user.id %}">Cart</a>                          -->
                                            <a class="dropdown-item" href="{% url 'users:updateuser' user.id %}">Edit</a>
                                            <a class="dropdown-item" onclick="logoutUser()">Logout</a>
                                        </div>
                                    </li>
                                </ul>        
                            </div> 
                        {% else %}
                            <a class="btn btn-outline-dark" href="{% url 'users:userlogin' %}" role="button">Login</a>
                        {% endif %}
                    </div>   
                </div>
            </div>
        </div>        
    </nav>
</body>
</html>