core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += [
    path('api-token-auth/', views.obtain_auth_token)
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from users.api import UserViewSet

app_name = 'users'
urlpatterns = [    
    
    path('login/', views.LoginView.as_view(), name="userlogin"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('<int:pk>/updateuser/', views.UpdateUserView.as_view(), name="updateuser"),
    path('userlist/', views.UserListView.as_view(), name="userlist"),
    path('<int:pk>/userpage/', views.UserPageView.as_view(), name="userpage"),
    path('<int:pk>/usercart/', views.UserCartView.as_view(), name="usercart"),
    path('<int:pk>/payment/', views.UserPayment.as_view(), name="payment"),
    path('<int:pk>/orderstatus/', views.OrderStatus.as_view(), name="orderstatus"),

    path('api/getuser/', UserViewSet.as_view({'get': 'get'})),
    path('api/getusers/', UserViewSet.as_view({'get': 'userlist'})),    
    path('api/updateuser/', UserViewSet.as_view({'post': 'update_user'})),
    path('api/users/register/', UserViewSet.as_view({'post': 'post'})),
    path('api/login/', UserViewSet.as_view({'post': 'userlogin'})),
    path('api/logout/', UserViewSet.as_view({'get': 'userlogout'})),

    
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

# Create your models here.

class CustomUser(AbstractUser):
    username = None    
    email = models.EmailField(('email address'), unique=True)
    is_seller = models.BooleanField(default=False)
    password2 = models.CharField(default="", max_length=20)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.get_or_create(user=instance)

users/views.py
from django.shortcuts import render
from products.models import Category, Product, SubCategory
from django.views.generic.base import TemplateView


class RegisterView(TemplateView):    
    template_name = 'users/registration.html'


class LoginView(TemplateView):
    template_name = 'users/login.html'


class UpdateUserView(TemplateView):
    template_name ="users/update_user.html"


class DashboardView(TemplateView):
    
    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        sub_categories = SubCategory.objects.all()
        categories = Category.objects.all()
        return render(request, "dashboard.html", {'products': products, 'categories': categories, 'sub_categories': sub_categories})

class UserListView(TemplateView):
    template_name = "users/user_list.html"


class UserCartView(TemplateView):    
    template_name = "users/user_cart.html"

class UserPageView(TemplateView):
    template_name = "users/user_page.html"

class UserPayment(TemplateView):
    template_name = "users/user_payment.html"

class OrderStatus(TemplateView):
    template_name = "users/order_status.html"
    

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/login.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">  
  <div class="center">  
    <h2 class="d-flex justify-content-center">Log In</h2>
    <div id="error" class="alert alert-danger" role="alert">
		
    </div>
    <form id="loginform">
      {% csrf_token %}              
        <div class="row align-items-center mb-2 mt-2">  
          
          <label for="email">Email address</label>
          <input type="email" class="form-control" id="email" placeholder="Enter Email">
          <span id="error" style="display:none;color:red;">Wrong email</span>

          <label for="password">Password</label>
          <input type="password" class="form-control" id="password" placeholder="Password">	
          
        </div>
      <br>
      <div class="text-center">
        <button type="submit" onclick="loginUser()" class="btn btn-info" id="loginbtn">Log In</button>
      </div>                                           
    </form>           
  </div>           
  <br>  
</div>
<p id="register" class="text-center">Don't have an account? <a href="{% url 'users:register' %}">Create an account</a>.</p>
{% endblock content %}

{% block extra_js %}
  <script type="text/javascript" src="{% static 'users/js/login.js' %}"></script>
{% endblock %}

templates/users/order_status.html
{% include 'base.html' %}
{% load static %}


{% block head %}
{% endblock %}

{% block content %}
<div class="container" id="order_status">
    <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
    <h4>Orders</h4>
    <table class="table table-hover text-center">
        <thead>
        <tr>            
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>            
            <th scope="col">Date Ordered</th> 
            <th scope="col">Status</th>               
        </tr>
        </thead>
        <tbody id="order-status">
        
        </tbody>
    </table>       
  </div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'products/js/order_status.js' %}"></script>
{% endblock %}

templates/users/registration.html
{% extends 'base.html' %}}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/register.css' %}">
{% endblock %}

{% block content %}
<div class="container">	
	
  	<div class="center">  
		<form id="registerform" class="needs-validation" novalidate>
			{% csrf_token %}      			
			<h2 class="d-flex justify-content-center">Register</h2>
			<div id="success" class="alert alert-success hidden" role="alert">
				
			</div>					
			<div class="row align-items-center mb-2 mt-2">

				<label for="first-name">First Name</label>
				<input type="text" class="form-control" id="first_name" placeholder="First Name" required>
				<div class="invalid-feedback">Please enter firstname.</div>

				<label for="last-name">Last Name</label>
				<input type="text" class="form-control" id="last_name" placeholder="Last Name" required>
				<div class="invalid-feedback">Please enter lastname.</div>

				<label for="email">Email address</label>
				<input type="email" class="form-control" id="email" placeholder="Enter Email" required>
				<div class="invalid-feedback">Please enter email.</div>	
				<span id="error" style="display:none;color:red;">Wrong email</span>
				

				<label for="password">Password</label>
				<input type="password" class="form-control" id="password" placeholder="Password" required>		
				<div class="invalid-feedback">Please enter password.</div>		

				<label for="password2">Confirm Password</label>
				<input type="password" class="form-control" id="password2" required>
				<span id='message'></span>
				<br>
				<div class="form-check mt-2">				
					<input type="checkbox" class="form-check-input" id="is_seller">				
					<label class="form-check-label" for="is-is_seller">Is Seller</label>
				</div>
			</div>						
			<div class="text-center">
				<button class="btn btn-primary" type="submit" id="registerbtn">Register</button>     
			</div>	 			      			                       
		</form>
	</div> 	
</div>
<p class="text-center mb-4">If you already have an account, <a href="{% url 'users:userlogin' %}">login</a> instead.</p>     
{% endblock %}

{% block extra_js %}
	<script type="text/javascript" src="{% static 'users/js/register.js' %}"></script>
{% endblock %}

templates/users/update_user.html
{% extends 'base.html' %}
{% load static %}


{% block head%}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/login.css' %}">
{% endblock %}

{% block content%}
<div class="container" id="update">
  <div class="center">
    <input type="hidden" value="{{ request.user.id }}" id="auth_user" onkeypress="return /[a-z]/i.test(event.key)">
    <form id="update_user">
        {% csrf_token %}
        <div class="form-group">
          <label for="fname">First Name</label>
          <input type="text" class="form-control" id="fname" placeholder="" onkeypress="return /[a-z]/i.test(event.key)">
        </div>
        <div class="form-group">
          <label for="lname">Last Name</label>
          <input type="text" class="form-control" id="lname" placeholder="">
        </div>
        <div class="text-center">
          <button class="btn btn-warning" type="submit">Update Details</button>     
      </div>
    </form>
  </div>  
</div>
{% endblock %}

{% block extra_js%}
  <script type="text/javascript" src="{% static 'users/js/update_user.js' %}"></script>
{% endblock %}

templates/users/user_cart.html
{% include 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'products/css/ordered.css' %}">   
{% endblock %}

{% block content %}
<div class="container">
  <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
  <div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">      
      <div class="col-md-8" id="cart">
        <div class="p-2">
            <h4>Shopping cart</h4>              
        </div>                    
        <div id='error' class='alert alert-danger' role='alert' style="display: none">            
        </div>
        <div>          
          <div id="usercart">

          </div>          
        </div>         
        <hr>
        <div class="offset-md-6">
          <p>Discount: <span id="discount" class="ml-5"></span></p>
          <p>Shipping Fee: <span id="fee" class="ml-3"></span></p>
          <h5>Total: <span id="total" class="ml-5"></span></h5>
        </div>
        
        <div id="totalprice" class="d-flex flex-row justify-content-between align-items-center p-2 bg-white mt-4 px-3 rounded">
          
        </div>        
        <div id="checkout" class="d-flex flex-row align-items-center mt-3 p-2 bg-white rounded">
          <button type="button" class="btn btn-warning btn-block btn-lg ml-2 pay-button text-white" data-toggle="modal" data-target="#deleteModal">Proceed to Pay</button>

          <div class='modal fade bd-example-modal-sm' id='deleteModal' tabindex='-1' role='dialog'>
            <div class='modal-dialog modal-dialog-centered' role='document'>
                <div class='modal-content'>
                    <div class='modal-body'>
                        Do you want to checkout?
                    </div>
                    <div class='modal-footer'>
                        <button type='button' class='btn btn-secondary text-white' data-dismiss='modal'>Close</button>
                        <a href="{% url 'users:payment' user.id %}" role='button' class='btn btn-warning' onclick="create_order()">Checkout</a>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>  
  </div>  
</div>

{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'products/js/ordered.js' %}"></script>    
    <script type="text/javascript" src="{% static 'products/js/item_count.js' %}"></script>
{% endblock %}

templates/users/user_list.html
{% include 'base.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
  <div class="container text-center" id="user_list"></div>
    {% if request.user.is_superuser %}  
      <table class="table table-hover text-center">
          <thead>
            <tr>            
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>            
              <th scope="col">Is Seller</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody id="userlist">
            
          </tbody>
      </table>  
    {% else %}
    <div class="text-center">
      You are not allowed to view this page
    </div>
    {% endif %}  
  </div>
{% endblock %}
{% block extra_js %}
  <script type="text/javascript" src="{% static 'users/js/userlist.js' %}"></script>
{% endblock %}

templates/users/user_page.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/view_user.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  {% if request.user.is_superuser %}
  <div id="userpage" class="text-center">

  </div>
  <br>
  <h3>Products</h3>
  <hr>
  <br>
  <div class="row" id="owned">
  
  </div>
  <br>
  <h3>Cart</h3>
  <hr>
  <div id="cart" class="text-center m-4">
    <table class="table table-hover">
      <thead>
        <tr>            
          <th scope="col">Product</th>
          <th scope="col">Quantity</th>            
          <th scope="col">Subtotal</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody id="usercart">
        
      </tbody>
    </table>
  </div>  
  <br>
  <h3>Orders</h3>   
  <hr> 
  <div id="order" class="text-center m-4">
    <table class="table table-hover">
      <thead>
        <tr>            
          <th scope="col">Product</th>
          <th scope="col">Quantity</th>            
          <th scope="col">Date Ordered</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody id="orders">        
      </tbody>
    </table>
  </div>  
  <br>
  <br>  
  {% else %}
  <div class="text-center">
    You are not allowed to view this page
  </div>  
  {% endif %}  
  
</div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'users/js/view_user.js' %}"></script>    
{% endblock %}

templates/users/user_payment.html
{% include 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'products/css/payment.css' %}">
{% endblock %}

{% block content %}
<div class="container py-5">
    <input  type="hidden" value="{{ request.user.id }}" id="auth_user">
    <!-- For demo purpose -->
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card ">
                <div class="card-header">
                    <div class="bg-white shadow-sm pt-4 pl-2 pr-2 pb-2">
                        
                        <ul role="tablist" class="nav bg-light nav-pills rounded nav-fill mb-3">
                            <li class="nav-item"> <a id="card" data-toggle="pill" href="#credit-card" class="nav-link active ">Credit Card </a> </li>
                            <li class="nav-item"> <a id="cod" data-toggle="pill" href="#COD" class="nav-link ">Cash on Delivery </a> </li>                            
                        </ul>
                    </div> 
                    
                    <div class="tab-content">

                        <div id="credit-card" class="tab-pane fade show active pt-3">
                            <form id="cardform">
                                {% csrf_token %}
                                <div class="form-group"> <label for="name">
                                        <h6>Card Owner</h6>
                                    </label> <input type="text" id="name" placeholder="Card Owner Name" required class="form-control "> </div>
                                <div class="form-group"> <label for="cardNumber">
                                        <h6>Card number</h6>
                                    </label>
                                    <div class="input-group"> <input type="text" id="cardNumber" placeholder="Valid card number" class="form-control " required>
                                        <div class="input-group-append"> <span class="input-group-text text-muted"> </span> </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-8">
                                        <div class="form-group"> <label><span class="hidden-xs">
                                                    <h6>Expiration Date</h6>
                                                </span></label>
                                            <div class="input-group"> <input type="number" placeholder="MM" id="expire_m" class="form-control" required> <input type="number" placeholder="YY" id="expire_y" class="form-control" required> </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group mb-4"> <label data-toggle="tooltip" title="Three digit CV code on the back of your card">
                                                <h6>CVV <i class="fa fa-question-circle d-inline"></i></h6>
                                            </label> <input id="cvv" type="text" required class="form-control"> 
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer"> <button id="Cardbtn" type="submit" class="subscribe btn btn-primary btn-block shadow-sm"> Confirm Payment </button>
                            </form>
                        </div>
                    </div>
                    
                    <div id="COD" class="tab-pane fade pt-3">
                        <form id="CODform" method="POST">
                            {% csrf_token %}
                            <div class="form-group"> <label for="address">
                                <h6 class="pb-2">Enter your Address</h6>
                            </label> <input type="text" id="address" placeholder="Address" required class="form-control "> </div> 
                            <p class="text-muted">After completing the payment process, you will be redirected back to the website to view details of your order. </p>
                            <div class="card-footer"> <button id="CODbtn" type="submit" class="subscribe btn btn-primary btn-block shadow-sm"> Confirm Payment </button>
                        </form>                                                                   
                    </div>                     
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'products/js/payment.js' %}"></script>
{% endblock %}